### ISSUE TITLE
uMIDI

### ISSUE THREAD

**Issue by theFork** [theFork/uMIDI-switcher#1]
uMIDI boards connected to the 9V power output of the switchers get destroyed somehow. Apparently this happens when an effect is connected to an external 9V output in reverse polarity.
- [x] Do the defective boards still respond to the PDI programmer?
- [ ] Construct a test circuit (without uMIDI board) and measure peak voltages when connecting a diode in forward direction to a 9V output
- [ ] Add a (defective) uMIDI board and observe the peaks at the in- and output of the 3.3V LDO. Do we exceed the MCUs maximum voltage ratings?
- [ ] Develop protection circuit, modify existing boards, test and update current design files.

**Comment by ghost** [comment]
Apparently, this can be fixed by re-installing the software. It looks like a block of data was somehow erased from FLASH memory. Here are two images - the first one was read out from the chip after the incident occured and the second one was is the same commit, rebuilt from scratch with make clean compile, flashed to the device and read back:
[flash-d5686b7-broken.hex.txt](https://github.com/theFork/uMIDI-switcher/files/201403/flash-d5686b7-broken.hex.txt)
[flash-d5686b7-ok.hex.txt](https://github.com/theFork/uMIDI-switcher/files/201402/flash-d5686b7-ok.hex.txt)

Creepy. oO

**Comment by theFork** [comment]
Reproduced with the following setup (I only wanted to update the firmware):
- Guitar Effects connected to the 9V outputs, floorboard (consuming from 12V) connected
- 12V wall adapter not connected (thus the floorboard should not matter)
- Used a long USB cable to connect a host via a USB hub
  - Hub support USB 3.x
  - Is externally powered from the far end of the room
  - Different grounds due to SMPS?

The same configuration has been tested without the USB hub. Error appears to be gone.

**Comment by theFork** [comment]
It happened again, this time without the USB hub.
- No USB devices is detected when connecting the board
- The red onboard LED flashes during startup, but the Tune/Mute LED does not turn on

avrdude -c atmelice_pdi -p x128a4u -U flash:r:flash.bin:b && hexdump flash.bin > [flash.hex.txt](https://github.com/theFork/uMIDI-switcher/files/230243/flash.hex.txt)

Reading out the fuses....

```
avrdude -c atmelice_pdi -p x128a4u -U fuse1:r:-:h
0x0

avrdude -c atmelice_pdi -p x128a4u -U fuse2:r:-:h
0xbf

avrdude -c atmelice_pdi -p x128a4u -U fuse4:r:-:h
0xfe

avrdude -c atmelice_pdi -p x128a4u -U fuse5:r:-:h
0xff
```

These values should be checked for sanity. Maybe this will give us a hint (?)

**Comment by ghost** [comment]
This issue can be closed, right?

**Comment by theFork** [comment]
Jepp.
